### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by ruthvikdevs** [azeezolaniran2016/react-calculator#5]
Hi @azeezolaniran2016 , I'm following the steps [here](https://codeburst.io/a-simple-calculator-app-using-react-and-node-42c9b0ea1df8)

and when I enter 'npm start' it throws below error.

----

npm start

> dexcalc@0.1.0 start C:\Users\ruthvikc\ReactDev
> babel-node ./server/server.js

C:\Users\ruthvikc\ReactDev\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:154
      throw err;
      ^

SyntaxError: C:\Users\ruthvikc\ReactDev\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5 data. Still to read: "��{\u0000\"\u0000p\u0000r\u0000e\u0000s\u0000e\u0000t\u0000s\u0000"
    at error (C:\Users\ruthvikc\ReactDev\node_modules\json5\lib\json5.js:56:25)
    at word (C:\Users\ruthvikc\ReactDev\node_modules\json5\lib\json5.js:393:13)
    at value (C:\Users\ruthvikc\ReactDev\node_modules\json5\lib\json5.js:493:56)
    at Object.parse (C:\Users\ruthvikc\ReactDev\node_modules\json5\lib\json5.js:508:18)
    at ConfigChainBuilder.addConfig (C:\Users\ruthvikc\ReactDev\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (C:\Users\ruthvikc\ReactDev\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:96:16)
    at buildConfigChain (C:\Users\ruthvikc\ReactDev\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:61:13)
    at OptionManager.init (C:\Users\ruthvikc\ReactDev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:354:58)
    at compile (C:\Users\ruthvikc\ReactDev\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\ruthvikc\ReactDev\node_modules\babel-register\lib\node.js:144:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dexcalc@0.1.0 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dexcalc@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ruthvikc\AppData\Roaming\npm-cache\_logs\2018-04-01T08_57_47_527Z-debug.log

**Comment by azeezolaniran2016** [comment]
@ruthvikdevs could you show the contents of your `babel.rc` file here?

**Comment by ruthvikdevs** [comment]
@azeezolaniran2016 - is it babel.rc or .babelrc


{"presets": ["env"]}

**Comment by azeezolaniran2016** [comment]
Oh okay. After this step "*$ echo '{"presets": ["es2015", "react"]}' >> .babelrc*", the content should actually be: `{"presets": ["es2015", "react"]}`.
I wrote the tutorial using a Unix machine. I'm not sure what of what differences/changes you might need using a Windows. I guess we can keep them documented as you create the issues.

**Comment by ruthvikdevs** [comment]
Initially I've created the same with what is given in the tutorial. I've just updated the babel to latest. That's all and no other change, but I'm still facing the error.

Error is occuring either with es2015 or env. Both

**Comment by azeezolaniran2016** [comment]
Can you clone the master branch and follow the setup steps just to be certain that the whole project works.

**Comment by ruthvikdevs** [comment]
If I clone the master branch and run 'npm start', there are no errors. But the screen is blank. I see no calculator in localhost:3030

**Comment by azeezolaniran2016** [comment]
Yea, run `npm run webpack` first. This creates the `bundle.js` file which is the calculator script.

**Comment by ruthvikdevs** [comment]
Error occurred: 


ERROR in ./client/index.js
Module build failed: SyntaxError: C:/Users/ruthvikc/Documents/GitHub/react-calculator/client/index.js: Unexpected token (9:2)

   7 | // on the element with id of 'app'
   8 | ReactDOM.render(
>  9 |   <Frame />, // mount our frame component
     |   ^
  10 |   document.getElementById('app')
  11 | );
  12 |

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-calculator@0.1.0 webpack: `webpack --config=webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-calculator@0.1.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
![image](https://user-images.githubusercontent.com/10224425/38175137-76b68ed4-35f5-11e8-8d2b-0b8b6227ee88.png)

**Comment by azeezolaniran2016** [comment]
Thanks for your patience @ruthvikdevs. I'm afraid I will need to reproduce this on a Windows machine, and hopefully create a fix. I don't have a Windows machine handy right now, but I should have this resolved soon. 
Please, could you also state what version of Windows you're running?

**Comment by krsunny** [comment]
Hi
getting this error
APPLEs-MacBook-Air:react-calculator apple$ npm start

> react-calculator@0.1.0 start /Users/apple/Desktop/react-calculator
> babel-node ./server/server.js

/Users/apple/Desktop/react-calculator/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:154
      throw err;
      ^

SyntaxError: /Users/apple/Desktop/react-calculator/.babelrc: Error while parsing JSON - Syntax error at line 2 column 1 of the JSON5 data. Still to read: "{\"presets\": [\"es2015"
    at error (/Users/apple/Desktop/react-calculator/node_modules/json5/lib/json5.js:56:25)
    at Object.parse (/Users/apple/Desktop/react-calculator/node_modules/json5/lib/json5.js:511:13)
    at ConfigChainBuilder.addConfig (/Users/apple/Desktop/react-calculator/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/Users/apple/Desktop/react-calculator/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
    at buildConfigChain (/Users/apple/Desktop/react-calculator/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/Users/apple/Desktop/react-calculator/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at compile (/Users/apple/Desktop/react-calculator/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/apple/Desktop/react-calculator/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/apple/Desktop/react-calculator/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-calculator@0.1.0 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-calculator@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-05-08T09_46_43_683Z-debug.log
